"""
Static tactical knowledge for Football Manager 2024.
Defines roles, formations, playing styles, and meta information.
"""

ROLE_DEFINITIONS = {
    "gk": {
        "name": "Goalkeeper",
        "short": "GK",
        "positions": ["GK"],
        "duties": ["defend"],
        "key_attrs": ["handling", "reflexes", "one_on_ones", "command_of_area", "communication"],
        "good_attrs": ["positioning", "aerial_reach", "kicking", "concentration", "agility"],
        "category": "goalkeeper",
    },
    "cd": {
        "name": "Central Defender",
        "short": "CD",
        "positions": ["DC"],
        "duties": ["defend", "stopper", "cover"],
        "key_attrs": ["marking", "tackling", "heading", "positioning", "strength"],
        "good_attrs": ["jumping_reach", "composure", "concentration", "bravery", "anticipation"],
        "category": "defender",
    },
    "bpd": {
        "name": "Ball-Playing Defender",
        "short": "BPD",
        "positions": ["DC"],
        "duties": ["defend", "stopper", "cover"],
        "key_attrs": ["passing", "composure", "first_touch", "marking", "tackling"],
        "good_attrs": ["heading", "positioning", "anticipation", "decisions", "concentration"],
        "category": "defender",
    },
    "fb": {
        "name": "Full-Back",
        "short": "FB",
        "positions": ["DL", "DR"],
        "duties": ["defend", "support", "attack"],
        "key_attrs": ["tackling", "marking", "positioning", "stamina", "work_rate"],
        "good_attrs": ["crossing", "pace", "teamwork", "anticipation", "concentration"],
        "category": "defender",
    },
    "wb": {
        "name": "Wing-Back",
        "short": "WB",
        "positions": ["WBL", "WBR", "DL", "DR"],
        "duties": ["defend", "support", "attack"],
        "key_attrs": ["crossing", "dribbling", "stamina", "pace", "work_rate"],
        "good_attrs": ["tackling", "off_the_ball", "teamwork", "acceleration", "technique"],
        "category": "defender",
    },
    "iwb": {
        "name": "Inverted Wing-Back",
        "short": "IWB",
        "positions": ["WBL", "WBR", "DL", "DR"],
        "duties": ["defend", "support", "attack"],
        "key_attrs": ["passing", "tackling", "decisions", "first_touch", "composure"],
        "good_attrs": ["technique", "vision", "positioning", "teamwork", "anticipation"],
        "category": "defender",
    },
    "dlp": {
        "name": "Deep-Lying Playmaker",
        "short": "DLP",
        "positions": ["DM", "MC"],
        "duties": ["defend", "support"],
        "key_attrs": ["passing", "vision", "first_touch", "technique", "composure"],
        "good_attrs": ["decisions", "teamwork", "anticipation", "concentration", "positioning"],
        "category": "midfielder",
    },
    "bwm": {
        "name": "Ball-Winning Midfielder",
        "short": "BWM",
        "positions": ["DM", "MC"],
        "duties": ["defend", "support"],
        "key_attrs": ["tackling", "marking", "aggression", "work_rate", "stamina"],
        "good_attrs": ["teamwork", "bravery", "anticipation", "strength", "positioning"],
        "category": "midfielder",
    },
    "bbm": {
        "name": "Box-to-Box Midfielder",
        "short": "BBM",
        "positions": ["MC"],
        "duties": ["support"],
        "key_attrs": ["stamina", "work_rate", "passing", "tackling", "off_the_ball"],
        "good_attrs": ["teamwork", "decisions", "anticipation", "pace", "technique"],
        "category": "midfielder",
    },
    "mez": {
        "name": "Mezzala",
        "short": "MEZ",
        "positions": ["MC"],
        "duties": ["support", "attack"],
        "key_attrs": ["dribbling", "passing", "off_the_ball", "technique", "acceleration"],
        "good_attrs": ["decisions", "vision", "first_touch", "stamina", "work_rate"],
        "category": "midfielder",
    },
    "if": {
        "name": "Inside Forward",
        "short": "IF",
        "positions": ["AML", "AMR"],
        "duties": ["support", "attack"],
        "key_attrs": ["dribbling", "finishing", "acceleration", "off_the_ball", "technique"],
        "good_attrs": ["first_touch", "flair", "pace", "composure", "decisions"],
        "category": "attacker",
    },
    "w": {
        "name": "Winger",
        "short": "W",
        "positions": ["AML", "AMR", "ML", "MR"],
        "duties": ["support", "attack"],
        "key_attrs": ["crossing", "dribbling", "pace", "acceleration", "technique"],
        "good_attrs": ["off_the_ball", "agility", "stamina", "first_touch", "flair"],
        "category": "attacker",
    },
    "ap": {
        "name": "Advanced Playmaker",
        "short": "AP",
        "positions": ["AMC", "MC"],
        "duties": ["support", "attack"],
        "key_attrs": ["passing", "vision", "technique", "first_touch", "decisions"],
        "good_attrs": ["composure", "flair", "off_the_ball", "dribbling", "anticipation"],
        "category": "midfielder",
    },
    "af": {
        "name": "Advanced Forward",
        "short": "AF",
        "positions": ["ST"],
        "duties": ["attack"],
        "key_attrs": ["finishing", "off_the_ball", "acceleration", "pace", "composure"],
        "good_attrs": ["dribbling", "first_touch", "technique", "anticipation", "decisions"],
        "category": "attacker",
    },
    "pf": {
        "name": "Pressing Forward",
        "short": "PF",
        "positions": ["ST"],
        "duties": ["defend", "support", "attack"],
        "key_attrs": ["work_rate", "aggression", "stamina", "off_the_ball", "teamwork"],
        "good_attrs": ["finishing", "bravery", "anticipation", "pace", "acceleration"],
        "category": "attacker",
    },
}


FORMATIONS = {
    "4231": {
        "name": "4-2-3-1",
        "positions": ["GK", "DL", "DC", "DC", "DR", "MC", "MC", "AML", "AMC", "AMR", "ST"],
        "default_roles": ["gk", "fb", "cd", "cd", "fb", "dlp", "bwm", "if", "ap", "if", "af"],
        "default_duties": [
            "defend", "support", "defend", "defend", "support",
            "defend", "support", "attack", "support", "attack", "attack",
        ],
        "tier_suitability": ["top", "upper", "mid"],
        "style_affinity": ["gegenpress", "vertical_tiki_taka", "control_possession"],
        "description": "Balanced formation with creative width and a double pivot. Dominant in the FM24 meta.",
    },
    "433": {
        "name": "4-3-3",
        "positions": ["GK", "DL", "DC", "DC", "DR", "DM", "MC", "MC", "AML", "AMR", "ST"],
        "default_roles": ["gk", "fb", "cd", "cd", "fb", "dlp", "bbm", "mez", "if", "w", "af"],
        "default_duties": [
            "defend", "support", "defend", "defend", "support",
            "defend", "support", "attack", "support", "attack", "attack",
        ],
        "tier_suitability": ["top", "upper", "mid"],
        "style_affinity": ["gegenpress", "tiki_taka", "vertical_tiki_taka"],
        "description": "Classic three-man midfield providing central overloads. Strong in transitions.",
    },
    "3421": {
        "name": "3-4-2-1",
        "positions": ["GK", "DC", "DC", "DC", "WBL", "WBR", "MC", "MC", "AML", "AMR", "ST"],
        "default_roles": ["gk", "cd", "bpd", "cd", "wb", "wb", "dlp", "bbm", "if", "if", "pf"],
        "default_duties": [
            "defend", "defend", "defend", "defend", "support",
            "support", "support", "support", "attack", "attack", "attack",
        ],
        "tier_suitability": ["top", "upper"],
        "style_affinity": ["gegenpress", "wing_play", "fluid_counter"],
        "description": "Width from wing-backs with narrow attacking midfielders cutting inside.",
    },
    "424": {
        "name": "4-2-4",
        "positions": ["GK", "DL", "DC", "DC", "DR", "MC", "MC", "AML", "AMR", "ST", "ST"],
        "default_roles": ["gk", "fb", "cd", "cd", "fb", "bwm", "bbm", "w", "w", "af", "pf"],
        "default_duties": [
            "defend", "defend", "defend", "defend", "defend",
            "defend", "support", "attack", "attack", "attack", "support",
        ],
        "tier_suitability": ["top"],
        "style_affinity": ["gegenpress", "wing_play", "route_one"],
        "description": "Ultra-attacking with four forwards. High risk, high reward.",
    },
    "442": {
        "name": "4-4-2",
        "positions": ["GK", "DL", "DC", "DC", "DR", "ML", "MC", "MC", "MR", "ST", "ST"],
        "default_roles": ["gk", "fb", "cd", "cd", "fb", "w", "bwm", "bbm", "w", "af", "pf"],
        "default_duties": [
            "defend", "support", "defend", "defend", "support",
            "support", "defend", "support", "support", "attack", "support",
        ],
        "tier_suitability": ["top", "upper", "mid", "lower"],
        "style_affinity": ["wing_play", "route_one", "direct_counter"],
        "description": "Traditional balanced shape. Reliable at all levels with clear partnerships.",
    },
    "442_diamond": {
        "name": "4-4-2 Diamond",
        "positions": ["GK", "DL", "DC", "DC", "DR", "DM", "MC", "MC", "AMC", "ST", "ST"],
        "default_roles": ["gk", "fb", "cd", "cd", "fb", "bwm", "bbm", "mez", "ap", "af", "pf"],
        "default_duties": [
            "defend", "support", "defend", "defend", "support",
            "defend", "support", "attack", "support", "attack", "support",
        ],
        "tier_suitability": ["top", "upper", "mid"],
        "style_affinity": ["tiki_taka", "control_possession", "vertical_tiki_taka"],
        "description": "Narrow midfield diamond dominating the centre. Relies on full-backs for width.",
    },
    "352": {
        "name": "3-5-2",
        "positions": ["GK", "DC", "DC", "DC", "WBL", "WBR", "DM", "MC", "MC", "ST", "ST"],
        "default_roles": ["gk", "cd", "bpd", "cd", "wb", "wb", "dlp", "bbm", "mez", "af", "pf"],
        "default_duties": [
            "defend", "defend", "defend", "defend", "support",
            "support", "defend", "support", "attack", "attack", "support",
        ],
        "tier_suitability": ["top", "upper", "mid"],
        "style_affinity": ["control_possession", "tiki_taka", "fluid_counter"],
        "description": "Midfield overload with width from wing-backs. Good for possession and counters.",
    },
    "343": {
        "name": "3-4-3",
        "positions": ["GK", "DC", "DC", "DC", "WBL", "WBR", "MC", "MC", "AML", "AMR", "ST"],
        "default_roles": ["gk", "cd", "bpd", "cd", "wb", "wb", "dlp", "bbm", "w", "if", "af"],
        "default_duties": [
            "defend", "defend", "defend", "defend", "attack",
            "attack", "defend", "support", "support", "attack", "attack",
        ],
        "tier_suitability": ["top", "upper"],
        "style_affinity": ["gegenpress", "wing_play", "vertical_tiki_taka"],
        "description": "Aggressive three-at-the-back with wide forwards. Requires quality wing-backs.",
    },
    "4141": {
        "name": "4-1-4-1",
        "positions": ["GK", "DL", "DC", "DC", "DR", "DM", "ML", "MC", "MC", "MR", "ST"],
        "default_roles": ["gk", "fb", "cd", "cd", "fb", "bwm", "w", "dlp", "bbm", "w", "pf"],
        "default_duties": [
            "defend", "support", "defend", "defend", "support",
            "defend", "support", "support", "support", "support", "attack",
        ],
        "tier_suitability": ["top", "upper", "mid", "lower"],
        "style_affinity": ["catenaccio", "direct_counter", "fluid_counter"],
        "description": "Defensively solid with a single holding midfielder screening the back four.",
    },
    "532": {
        "name": "5-3-2",
        "positions": ["GK", "WBL", "DC", "DC", "DC", "WBR", "MC", "MC", "MC", "ST", "ST"],
        "default_roles": ["gk", "wb", "cd", "bpd", "cd", "wb", "bwm", "dlp", "bbm", "af", "pf"],
        "default_duties": [
            "defend", "support", "defend", "defend", "defend",
            "support", "defend", "support", "support", "attack", "support",
        ],
        "tier_suitability": ["mid", "lower"],
        "style_affinity": ["catenaccio", "direct_counter", "route_one"],
        "description": "Defensive shape with five across the back. Wing-backs provide attacking outlets.",
    },
}


PLAYING_STYLES = {
    "gegenpress": {
        "name": "Gegenpress",
        "mentality": "positive",
        "required_attrs": {
            "stamina": 13,
            "work_rate": 13,
            "teamwork": 12,
            "aggression": 11,
            "anticipation": 12,
            "bravery": 11,
        },
        "description": "High-intensity pressing to win the ball back immediately after losing it.",
        "tier_affinity": ["top", "upper"],
    },
    "tiki_taka": {
        "name": "Tiki-Taka",
        "mentality": "positive",
        "required_attrs": {
            "passing": 14,
            "first_touch": 13,
            "technique": 13,
            "vision": 12,
            "composure": 12,
            "decisions": 12,
        },
        "description": "Short passing, possession-based style focused on creating space through movement.",
        "tier_affinity": ["top"],
    },
    "vertical_tiki_taka": {
        "name": "Vertical Tiki-Taka",
        "mentality": "positive",
        "required_attrs": {
            "passing": 13,
            "first_touch": 12,
            "technique": 12,
            "off_the_ball": 12,
            "decisions": 12,
            "pace": 11,
        },
        "description": "Possession with purpose \u2014 direct vertical passing to break lines quickly.",
        "tier_affinity": ["top", "upper"],
    },
    "fluid_counter": {
        "name": "Fluid Counter-Attack",
        "mentality": "cautious",
        "required_attrs": {
            "pace": 13,
            "acceleration": 13,
            "off_the_ball": 12,
            "passing": 11,
            "decisions": 11,
            "composure": 11,
        },
        "description": "Absorb pressure then launch quick, incisive counter-attacks through the middle.",
        "tier_affinity": ["mid", "lower"],
    },
    "wing_play": {
        "name": "Wing Play",
        "mentality": "positive",
        "required_attrs": {
            "crossing": 13,
            "dribbling": 12,
            "pace": 12,
            "stamina": 12,
            "off_the_ball": 11,
            "heading": 11,
        },
        "description": "Attack through the flanks with crosses into the box for aerial threats.",
        "tier_affinity": ["top", "upper", "mid", "lower"],
    },
    "route_one": {
        "name": "Route One",
        "mentality": "balanced",
        "required_attrs": {
            "heading": 13,
            "strength": 13,
            "off_the_ball": 12,
            "work_rate": 12,
            "long_shots": 11,
            "passing": 10,
        },
        "description": "Direct, long-ball football bypassing the midfield. Relies on physical strikers.",
        "tier_affinity": ["lower"],
    },
    "catenaccio": {
        "name": "Catenaccio",
        "mentality": "defensive",
        "required_attrs": {
            "marking": 13,
            "tackling": 13,
            "positioning": 13,
            "concentration": 13,
            "anticipation": 12,
            "composure": 11,
        },
        "description": "Ultra-defensive organisation with disciplined shape and rare counter-attacks.",
        "tier_affinity": ["mid", "lower"],
    },
    "control_possession": {
        "name": "Control Possession",
        "mentality": "balanced",
        "required_attrs": {
            "passing": 13,
            "first_touch": 12,
            "decisions": 12,
            "composure": 12,
            "teamwork": 12,
            "technique": 11,
        },
        "description": "Patient build-up play keeping the ball to control the tempo of the match.",
        "tier_affinity": ["top", "upper", "mid"],
    },
    "direct_counter": {
        "name": "Direct Counter",
        "mentality": "defensive",
        "required_attrs": {
            "pace": 12,
            "acceleration": 12,
            "marking": 12,
            "tackling": 12,
            "off_the_ball": 11,
            "stamina": 12,
        },
        "description": "Sit deep and defend in numbers, then hit quickly on the break with pace.",
        "tier_affinity": ["mid", "lower"],
    },
}


FM24_META = {
    "op_roles": ["if", "mez", "bpd", "af", "iwb"],
    "op_combos": [
        {"roles": ["if", "mez"], "reason": "Inside Forward pulling wide creates space for Mezzala runs"},
        {"roles": ["iwb", "if"], "reason": "Inverted Wing-Back provides width while IF cuts inside"},
        {"roles": ["dlp", "bwm"], "reason": "Classic double pivot balancing creativity and ball recovery"},
        {"roles": ["af", "pf"], "reason": "AF makes runs in behind while PF drops deep to link play"},
    ],
    "tier_recommendations": {
        "top": {
            "formations": ["4231", "433", "343"],
            "styles": ["gegenpress", "tiki_taka", "vertical_tiki_taka"],
        },
        "upper": {
            "formations": ["4231", "433", "352"],
            "styles": ["gegenpress", "control_possession", "vertical_tiki_taka"],
        },
        "mid": {
            "formations": ["442", "4141", "442_diamond"],
            "styles": ["control_possession", "wing_play", "fluid_counter"],
        },
        "lower": {
            "formations": ["442", "532", "4141"],
            "styles": ["direct_counter", "route_one", "catenaccio"],
        },
    },
    "engine_tips": [
        "Inverted Wing-Backs are overpowered in FM24 when paired with wide forwards.",
        "Inside Forwards on Attack duty generate the most goals from wide positions.",
        "Mezzala on Attack is one of the highest-scoring midfielder roles.",
        "Gegenpress is the dominant meta tactic but requires high stamina across the squad.",
        "Three-at-the-back formations are vulnerable to fast wingers in wide areas.",
    ],
    "top_leagues": [
        "Premier League",
        "LaLiga",
        "Serie A",
        "Bundesliga",
        "Ligue 1",
    ],
}


POSITION_TO_ROLES: dict[str, list[str]] = {}
for _role_id, _role_data in ROLE_DEFINITIONS.items():
    for _pos in _role_data["positions"]:
        POSITION_TO_ROLES.setdefault(_pos, []).append(_role_id)
